export const ActionTypes = {
    GET_EMPLOYEES: "GET_EMPLOYEES",
    ADD_EMPLOYEE: "ADD_EMPLOYEE",
    SELECT_EMPLOYEE: "SELECT_EMPLOYEE",
    DELETE_SELECTED_EMPLOYEE: "DELETE_SELECTED_EMPLOYEE",
    UPDATE_SELECTED_EMPLOYEE: "UPDATE_SELECTED_EMPLOYEE",
    LOGIN: "LOGIN",
    REGISTER: "REGISTER",
    LOGOUT: "LOGOUT"
}